### ISSUE TITLE
cleanup

### ISSUE THREAD

**Issue by joreg** [vvvv/VL.Devices.IDS#5]
- [x] VideoIn: defaults for resolution/fps should be: 640/480@30
- [x] Add helpflags to nodes
- [x] VideoIn: make sure it doesn't crash with out-of-range resolution/fps
- [x] VideoIn: add "Enabled" input
- [x] AvailableProperties: alphabetically sort output
- [x] make DeviceDescriptor, IConfiguration, IDSDevices, IDSDeviceDefinition advanced
- [x] ConfigWriter: input "Video In" > "Input"

**Comment by joreg** [comment]
@rmtttt can we remove double mention of camera type from enum entr?
![grafik](https://github.com/user-attachments/assets/3e1d462d-3980-42d7-a2e5-37a240fb80b6)

**Comment by rmtttt** [comment]
![Screenshot 2024-08-05 194342](https://github.com/user-attachments/assets/17bf2abe-a897-48bb-ab79-dbaea270257a)
these are the options, atm is the first one.

**Comment by rmtttt** [comment]
changed to vendor-model/SN
